#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
HEADER_PATH=""
SKIP_BUMP="${SKIP_VERSION_BUMP:-0}"

while [ $# -gt 0 ]; do
    case "$1" in
        --repo-root)
            REPO_ROOT="$2"
            shift 2
            ;;
        --header)
            HEADER_PATH="$2"
            shift 2
            ;;
        --no-bump)
            SKIP_BUMP=1
            shift
            ;;
        *)
            echo "Unknown option: $1" >&2
            echo "Usage: $0 [--repo-root <path>] [--header <path>] [--no-bump]" >&2
            exit 1
            ;;
    esac
done

VERSION_FILE="$REPO_ROOT/version.txt"
if [ ! -f "$VERSION_FILE" ]; then
    echo "Error: $VERSION_FILE not found." >&2
    exit 1
fi

CURRENT_VERSION=$(tr -d '\r\n' < "$VERSION_FILE")
if [[ "$CURRENT_VERSION" =~ ^([vV]?)([0-9]+)\.([0-9]+)\.([0-9]+)([^0-9].*)?$ ]]; then
    VERSION_PREFIX="${BASH_REMATCH[1]}"
    VERSION_MAJOR="${BASH_REMATCH[2]}"
    VERSION_MINOR="${BASH_REMATCH[3]}"
    VERSION_PATCH="${BASH_REMATCH[4]}"
    VERSION_SUFFIX="${BASH_REMATCH[5]}"
else
    echo "Error: Invalid version format in $VERSION_FILE: '$CURRENT_VERSION'" >&2
    echo "Expected format: v<major>.<minor>.<patch> (optional non-numeric suffix allowed)" >&2
    exit 1
fi

FINAL_VERSION="$CURRENT_VERSION"
if [ "$SKIP_BUMP" != "1" ]; then
    NEXT_PATCH=$((VERSION_PATCH + 1))
    FINAL_VERSION="${VERSION_PREFIX}${VERSION_MAJOR}.${VERSION_MINOR}.${NEXT_PATCH}${VERSION_SUFFIX}"
    printf "%s\n" "$FINAL_VERSION" > "$VERSION_FILE"
    echo "Version incremented: $CURRENT_VERSION -> $FINAL_VERSION"
else
    echo "Version bump skipped; using: $FINAL_VERSION"
fi

if [ -d "$REPO_ROOT/rp" ]; then
    printf "%s\n" "$FINAL_VERSION" > "$REPO_ROOT/rp/version.txt"
fi
if [ -d "$REPO_ROOT/target" ]; then
    printf "%s\n" "$FINAL_VERSION" > "$REPO_ROOT/target/version.txt"
fi

if [ -n "$HEADER_PATH" ]; then
    mkdir -p "$(dirname "$HEADER_PATH")"
    cat > "$HEADER_PATH" <<EOF
/* Auto-generated by tools/bump_version.sh */
#ifndef BUILD_VERSION_H
#define BUILD_VERSION_H
#define BUILD_RELEASE_VERSION "$FINAL_VERSION"
#endif /* BUILD_VERSION_H */
EOF
    echo "Wrote $HEADER_PATH"
fi
